import { ActionTypeEnum, PluginRecord } from "../../../../../src/types/Manager";
import { t } from "../../../../config/lang";
import { SystemIcons } from "../asset/icon";

export const SystemPlugin: PluginRecord = {
    name: "system",
    title: t("system.title"),
    version: "1.0.0",
    logo: SystemIcons.pluginSystem,
    description: t("system.desc"),
    main: "<root>/page/system.html",
    preload: "<system>",
    actions: [
        {
            name: "page-data",
            title: t("system.dataCenter"),
            type: ActionTypeEnum.WEB,
            icon: SystemIcons.database,
            matches: [t("system.dataCenter"), "data"] as any,
        },
        {
            name: "page-setting",
            title: t("system.functionSettings"),
            type: ActionTypeEnum.WEB,
            icon: SystemIcons.pluginSystem,
            matches: [t("system.functionSettings"), "setting"] as any,
        },
        {
            name: "page-plugin",
            title: t("system.pluginManagement"),
            type: ActionTypeEnum.WEB,
            icon: SystemIcons.plugin,
            matches: [t("system.pluginManagement"), "plugin"] as any,
        },
        {
            name: "page-action",
            title: t("system.actionManagement"),
            type: ActionTypeEnum.WEB,
            icon: SystemIcons.command,
            matches: [t("system.actionManagement"), "action"] as any,
        },
        {
            name: "page-file",
            title: t("system.fileLaunch"),
            type: ActionTypeEnum.WEB,
            icon: SystemIcons.folder,
            matches: [t("system.fileLaunch"), "file"] as any,
        },
        {
            name: "page-launch",
            title: t("system.hotkeys"),
            type: ActionTypeEnum.WEB,
            icon: SystemIcons.thunder,
            matches: [t("system.hotkeys"), "launch"] as any,
        },
        {
            name: "about",
            title: t("system.about"),
            type: ActionTypeEnum.CODE,
            icon: SystemIcons.about,
            matches: [t("system.about"), "about"] as any,
        },
        {
            name: "screenshot",
            title: t("system.screenshot"),
            type: ActionTypeEnum.CODE,
            icon: SystemIcons.screenshot,
            matches: [t("system.screenshot"), "screenshot", "snapshot"] as any,
        },
        {
            name: "colorPicker",
            title: t("system.colorPicker"),
            type: ActionTypeEnum.CODE,
            icon: SystemIcons.colorPicker,
            matches: [t("system.colorPicker"), "ColorPicker"] as any,
        },
        {
            name: "screenRecord",
            title: t("system.screenRecord"),
            type: ActionTypeEnum.CODE,
            icon: SystemIcons.screenRecord,
            matches: [t("system.screenRecord"), "ScreenRecord"] as any,
        },
        {
            name: "guide",
            title: t("nav.guide"),
            type: ActionTypeEnum.CODE,
            icon: SystemIcons.guide,
            matches: [t("nav.guide"), "guide"] as any,
        },
        {
            name: "lock",
            title: t("system.lockScreen"),
            type: ActionTypeEnum.CODE,
            icon: SystemIcons.lock,
            matches: [t("system.lockScreen"), "lock"] as any,
        },
        {
            name: "ip",
            title: t("system.lanIP"),
            type: ActionTypeEnum.CODE,
            icon: SystemIcons.ip,
            matches: [t("system.lanIP")] as any,
        },
    ],
};
